### NUMPY

#### 1. Create a NumPy array containing integers from 1 to 10.

In [1]:
import numpy as np

In [2]:
n1 = np.arange(1,11)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 2. Create a 2D NumPy array with shape (3, 4) filled with random float values between 0 and 1.

In [3]:
n2 = np.random.rand(3,4)
n2

array([[0.58022661, 0.17070165, 0.97951767, 0.46667753],
       [0.59665716, 0.51648971, 0.33706588, 0.74251813],
       [0.04172325, 0.52240536, 0.97526588, 0.3534865 ]])

#### 3. Given the following NumPy array: arr = np.array([10, 20, 30, 40, 50]) Add 5 to each element of the array.

In [4]:
arr = np.array([10, 20, 30, 40, 50])

print(arr+5)

[15 25 35 45 55]


#### 4. Given two NumPy arrays: arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8]). Concatenate them into a single array.


In [5]:
arr1 = np.array([1, 2, 3, 4]) 
arr2 = np.array([5, 6, 7, 8])

arr3 = np.concatenate((arr1,arr2))
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

#### 5. Create a NumPy array of 10 elements with equally spaced values from 0 to 9.


In [6]:
n5 = np.linspace(0,9,10)
n5

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 6. Given a NumPy array: arr = np.array([1, 2, 3, 4, 5, 6]). Reverse the elements in the array.


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])

np.flip(arr)

array([6, 5, 4, 3, 2, 1])

#### 7. Create a 3x3 identity matrix using NumPy.


In [8]:
n7 = np.identity(3)
n7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Calculate the mean, median, and standard deviation of the following NumPy array: arr = np.array([15, 20, 25, 30, 35])


In [9]:
arr = np.array([15, 20, 25, 30, 35])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))

Mean: 25.0
Median: 25.0
Standard deviation: 7.0710678118654755


#### 9. Given a 2D NumPy array: arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]). Get the diagonal elements of the array.

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)
print("Diagonal elements are:", np.diag(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal elements are: [1 5 9]


#### 10. Create a NumPy array of 10 random integers between 1 and 100 (inclusive).


In [11]:
np.random.randint(1,101,10)

array([26, 97, 16, 17, 14, 79, 63, 62,  1, 31])

#### 11. Create a 2D NumPy array of shape (5, 5) with random integers between 1 and 50(inclusive).


In [12]:
np.random.randint(1,51,size=(5,5))

array([[ 3, 29, 26, 15, 18],
       [46,  7, 23, 46, 33],
       [20,  3, 48, 25, 26],
       [35, 40, 37,  2,  7],
       [19, 24, 28,  8, 24]])

#### 12. Given a 2D NumPy array: arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]). Calculate the sum of all the elements in the array.


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Sum of all elements:", np.sum(arr))

Sum of all elements: 45


#### 13. Create a NumPy array with 100 evenly spaced values between 0 and 1 (inclusive) and reshape it into a 10x10 matrix.


In [14]:
n13 = np.linspace(0,1,100)

n13.reshape((10,10))

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

#### 14. Given two NumPy arrays:
arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([4, 5, 6, 7, 8])
Find the common elements between the two arrays.


In [15]:
arr1 = np.array([1, 2, 3, 4]) 
arr2 = np.array([4, 5, 6, 7, 8])

print(np.intersect1d(arr1,arr2))

[4]


#### 15. Create a NumPy array containing 10 random integers between -50 and 50 (inclusive). Replace all negative values in the array with 0.


In [16]:
n15 = np.random.randint(-50,51,10)
print(n15)

n15[n15<0] = 0

print(n15)

[-34  25 -50  39 -12  13 -37 -33 -24 -10]
[ 0 25  0 39  0 13  0  0  0  0]


#### 16. Given a 2D NumPy array:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Calculate the sum of each row and each column separately.


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

print("Sum of each row:", np.sum(arr, axis = 1))
print("Sum of each column:", np.sum(arr, axis = 0))

Sum of each row: [ 6 15 24]
Sum of each column: [12 15 18]


#### 17. Create a NumPy array of shape (6, 6) with diagonal elements as 1, 2, 3, 4, 5, and 6, and all other elements as 0.


In [18]:
n17 = np.diag([1, 2, 3, 4, 5, 6])
n17

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

#### 18. Given a NumPy array:
arr = np.array([1, 2, 3, 4, 5])
Normalize the array so that the values range from 0 to 1.


In [19]:
arr = np.array([1, 2, 3, 4, 5])

norm_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("Normalised array:", norm_arr)

Normalised array: [0.   0.25 0.5  0.75 1.  ]


#### 19. Create a NumPy array with 20 random integers between 1 and 100 (inclusive). Find the maximum value and its index in the array.


In [20]:
#Solution 1
n19 = np.random.randint(1,101,20)

print("Array:",n19)
print("Maximum value:", n19.max())
print("The index of maximum value:", n19.argmax())


Array: [97 60 39 60 10 14 49 97 58 20 28 55 97 11 84 42 27 24 25 12]
Maximum value: 97
The index of maximum value: 0


In [21]:
#Solution 2
arr = np.random.randint(1,101,20)
print("Array:",arr)

print("Maximum value:", arr.max())
print("The index of maximum value:", np.where(arr == arr.max()))


Array: [ 47  75  55  82  27  51  40 100  94  52   5  84  28  83  71  22  71  72
  99  97]
Maximum value: 100
The index of maximum value: (array([7], dtype=int64),)


#### 20. Given two NumPy arrays:
arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8])
Compute the element-wise product of the two arrays.


In [22]:
arr1 = np.array([1, 2, 3, 4]) 
arr2 = np.array([5, 6, 7, 8]) 

np.multiply(arr1,arr2)

array([ 5, 12, 21, 32])